
package com.mayuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Compute", targetNamespace = "http://mayuri.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Compute {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://mayuri.com")
    @RequestWrapper(localName = "add", targetNamespace = "http://mayuri.com", className = "com.mayuri.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://mayuri.com", className = "com.mayuri.AddResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "http://mayuri.com")
        int a,
        @WebParam(name = "b", targetNamespace = "http://mayuri.com")
        int b);

}
