
package com.mayuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ComputeService", targetNamespace = "http://mayuri.com", wsdlLocation = "http://localhost:8080/CalculateSOAPWebServices/services/Compute?wsdl")
public class ComputeService
    extends Service
{

    private final static URL COMPUTESERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPUTESERVICE_EXCEPTION;
    private final static QName COMPUTESERVICE_QNAME = new QName("http://mayuri.com", "ComputeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CalculateSOAPWebServices/services/Compute?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPUTESERVICE_WSDL_LOCATION = url;
        COMPUTESERVICE_EXCEPTION = e;
    }

    public ComputeService() {
        super(__getWsdlLocation(), COMPUTESERVICE_QNAME);
    }

    public ComputeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPUTESERVICE_QNAME, features);
    }

    public ComputeService(URL wsdlLocation) {
        super(wsdlLocation, COMPUTESERVICE_QNAME);
    }

    public ComputeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPUTESERVICE_QNAME, features);
    }

    public ComputeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComputeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Compute
     */
    @WebEndpoint(name = "Compute")
    public Compute getCompute() {
        return super.getPort(new QName("http://mayuri.com", "Compute"), Compute.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Compute
     */
    @WebEndpoint(name = "Compute")
    public Compute getCompute(WebServiceFeature... features) {
        return super.getPort(new QName("http://mayuri.com", "Compute"), Compute.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPUTESERVICE_EXCEPTION!= null) {
            throw COMPUTESERVICE_EXCEPTION;
        }
        return COMPUTESERVICE_WSDL_LOCATION;
    }

}
